# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField(null=True)),
                ('research', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.IntegerField(default=0)),
                ('RA1_1_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('RA1_1_loa', models.IntegerField(choices=[(0, 'No Added Value'), (5, 'Improved'), (10, 'Enhanced'), (15, 'Superior'), (20, 'Conserving')], default=0)),
                ('RA1_1_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('RA1_1_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('RA1_2_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('RA1_2_loa', models.IntegerField(choices=[(0, 'No Added Value'), (2, 'Improved'), (4, 'Enhanced'), (7, 'Superior'), (12, 'Conserving')], default=0)),
                ('RA1_2_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('RA1_2_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('RA1_4_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('RA1_4_loa', models.IntegerField(choices=[(0, 'No Added Value'), (4, 'Improved'), (7, 'Enhanced'), (10, 'Superior'), (16, 'Conserving')], default=0)),
                ('RA1_4_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('RA1_4_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('RA1_5_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('RA1_5_loa', models.IntegerField(choices=[(0, 'No Added Value'), (1, 'Improved'), (4, 'Enhanced'), (7, 'Superior'), (11, 'Conserving'), (16, 'Restorative')], default=0)),
                ('RA1_5_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('RA1_5_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('RA1_6_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('RA1_6_loa', models.IntegerField(choices=[(0, 'No Added Value'), (2, 'Improved'), (4, 'Enhanced'), (6, 'Superior'), (8, 'Conserving')], default=0)),
                ('RA1_6_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('RA1_6_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('RA2_2_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('RA2_2_loa', models.IntegerField(choices=[(0, 'No Added Value'), (1, 'Improved'), (4, 'Enhanced'), (8, 'Superior'), (12, 'Conserving')], default=0)),
                ('RA2_2_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('RA2_2_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('RA3_1_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('RA3_1_loa', models.IntegerField(choices=[(0, 'No Added Value'), (2, 'Improved'), (4, 'Enhanced'), (9, 'Superior'), (17, 'Conserving'), (22, 'Restorative')], default=0)),
                ('RA3_1_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('RA3_1_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('RA3_2_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('RA3_2_loa', models.IntegerField(choices=[(0, 'No Added Value'), (4, 'Improved'), (9, 'Enhanced'), (13, 'Superior'), (17, 'Conserving'), (22, 'Restorative')], default=0)),
                ('RA3_2_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('RA3_2_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('RA3_3_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('RA3_3_loa', models.IntegerField(choices=[(0, 'No Added Value'), (1, 'Improved'), (3, 'Enhanced'), (5, 'Superior'), (8, 'Conserving')], default=0)),
                ('RA3_3_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('RA3_3_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('NW1_1_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('NW1_1_loa', models.IntegerField(choices=[(0, 'No Added Value'), (3, 'Improved'), (7, 'Enhanced'), (12, 'Superior'), (16, 'Conserving'), (24, 'Restorative')], default=0)),
                ('NW1_1_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('NW1_1_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('NW2_2_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('NW2_2_loa', models.IntegerField(choices=[(0, 'No Added Value'), (2, 'Improved'), (4, 'Enhanced'), (9, 'Superior'), (17, 'Conserving'), (24, 'Restorative')], default=0)),
                ('NW2_2_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('NW2_2_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('NW2_3_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('NW2_3_loa', models.IntegerField(choices=[(0, 'No Added Value'), (1, 'Improved'), (2, 'Enhanced'), (5, 'Superior'), (9, 'Conserving'), (12, 'Restorative')], default=0)),
                ('NW2_3_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('NW2_3_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('NW2_4_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('NW2_4_loa', models.IntegerField(choices=[(0, 'No Added Value'), (2, 'Improved'), (4, 'Enhanced'), (9, 'Superior'), (14, 'Conserving'), (18, 'Restorative')], default=0)),
                ('NW2_4_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('NW2_4_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('NW3_1_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('NW3_1_loa', models.IntegerField(choices=[(0, 'No Added Value'), (2, 'Improved'), (5, 'Enhanced'), (9, 'Superior'), (15, 'Conserving'), (18, 'Restorative')], default=0)),
                ('NW3_1_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('NW3_1_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('RR1_1_inc', models.IntegerField(choices=[(0, 'Include'), (1, 'Exclude')], default=0)),
                ('RR1_1_loa', models.IntegerField(choices=[(0, 'No Added Value'), (5, 'Improved'), (8, 'Enhanced'), (14, 'Superior'), (18, 'Conserving'), (25, 'Restorative')], default=0)),
                ('RR1_1_exp', models.TextField(max_length=1000, null=True, blank=True)),
                ('RR1_1_cost', models.IntegerField(choices=[(-3, '--'), (-2, 'Signficant Savings'), (-1, 'Some Savings'), (0, 'Neutral'), (1, 'Some Cost'), (2, 'Significant Cost')], default=0)),
                ('engineer', models.ForeignKey(to='engineer.Engineer')),
            ],
        ),
    ]
